### ISSUE TITLE
Did liboofem lack the material module of 'DruckerPrager'?

### ISSUE THREAD

**Issue by Dez2018** [stranskyjan/dem-fem-coupling#1]
Hi Jan,
I am trying your surface coupler of DEM and FEM code and I tried to modify the material of fem by 'mat = liboofem.druckerprager(1, domain, tAlpha=0, d=1960, E=2e6, n=0.23, iys=2e4, alpha=0.23, alphasi=0.22)', but the error message showed that 'no module of 'druckerprager'', I tried other names like DruckerPrager, DP or druckerPrager, they didn't work. So did the liboofem lack the module of it? If so, how to invoke that material when I make the coupler of DEM and FEM?
Thanks,
De Zhang

**Comment by Dez2018** [comment]
Hi Jan,
Thanks, I have read the answer by you on the yade launchpad~
Best regards,
Dez

**Comment by stranskyjan** [comment]
for backward reference:
https://answers.launchpad.net/yade/+question/676855
