### ISSUE TITLE
surf1 example: dynamic module does not define init function (initlibyade)

### ISSUE THREAD

**Issue by zoheir1928** [stranskyjan/dem-fem-coupling#10]
Hi Jan,

When running surf1 example, I get the following error:
I would appreciate your thoughts on this.
~/FEMDEM/Installation$ make -f makefile all

# set usePolyhedra=True if poly option is set
# use profiler or not
python -m cProfile -o /tmp/surf1.pro surf1.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/cProfile.py", line 200, in <module>
    main()
  File "/usr/lib/python2.7/cProfile.py", line 193, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/usr/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/usr/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "surf1.py", line 9, in <module>
    import libyade
ImportError: dynamic module does not define init function (initlibyade)
makefile:41: recipe for target 'example' failed
make: *** [example] Error 1

**Comment by stranskyjan** [comment]
> ImportError: dynamic module does not define init function (initlibyade)

this indicates that python tries to import some shared library `libyade`, not the intended `libyade.py` from `demfem/install` directory

Do you have another Yade installed on the system?

**Comment by zoheir1928** [comment]
I do not think so! is there a way to make sure there is only one Yade installed? 
Can you think of any other reason behind this error?
Much appreciated

Zoheir

**Comment by stranskyjan** [comment]
what is the output of terminal commands:
```
sudo updatedb
locate libyade
```
?

**Comment by zoheir1928** [comment]
Here is the output:

/home/zoheir/FEMDEM/Installation/_build/install/libyade.py
/home/zoheir/FEMDEM/Installation/_build/install/libyade.so
/home/zoheir/FEMDEM/Installation/_build/yade/build/_build/yade/install/lib/x86_64-linux-gnu/yade/libyade.so
/home/zoheir/FEMDEM/Installation/_build/yade/build/lib/x86_64-linux-gnu/libyade.so
/usr/lib/x86_64-linux-gnu/yade/libyade.so
/usr/share/doc/libyade
/usr/share/doc/libyade/changelog.Debian.gz
/usr/share/doc/libyade/copyright
/usr/share/lintian/overrides/libyade
/var/cache/apt/archives/libyade_2018.02b-1_amd64.deb
/var/lib/dpkg/info/libyade:amd64.list
/var/lib/dpkg/info/libyade:amd64.md5sums

**Comment by stranskyjan** [comment]
it seems python is trying to import one of libyade.so files instead of libyade.py file..

could you try instead of
```python
import libyade
```
use
```python
import imp
libyade = imp.load_source("libyade","/home/zoheir/FEMDEM/Installation/_build/install/libyade.py")
```
?

**Comment by zoheir1928** [comment]
This time, it could not find "libyade.py" with an error: No such file or directory. There was a broken symbolic link.
I tried re-installing the codes using your makefile that I remembered during my first installation, I came across this error:
mkdir -p _build/oofem
mkdir -p _build/yade
mkdir -p _build/install
rm -rf _build/oofem/source-orig
wget http://www.oofem.org/cgi-bin/OOFEM/download.cgi?download=oofem-2.5.zip -O _build/oofem/oofem.zip
--2020-01-09 12:17:17--  http://www.oofem.org/cgi-bin/OOFEM/download.cgi?download=oofem-2.5.zip
Resolving www.oofem.org (www.oofem.org)... 147.32.130.71
Connecting to www.oofem.org (www.oofem.org)|147.32.130.71|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.oofem.org/download/oofem-2.5.zip [following]
--2020-01-09 12:17:18--  http://www.oofem.org/download/oofem-2.5.zip
Reusing existing connection to www.oofem.org:80.
HTTP request sent, awaiting response... 200 OK
Length: 14249792 (14M) [application/zip]
Saving to: ‘_build/oofem/oofem.zip’

_build/oofem/oofem. 100%[===================>]  13.59M  2.79MB/s    in 8.8s    

2020-01-09 12:17:27 (1.55 MB/s) - ‘_build/oofem/oofem.zip’ saved [14249792/14249792]

unzip -q -o _build/oofem/oofem.zip
mv oofem-2.5 _build/oofem/source-orig
rm -rf _build/oofem/source
cp -r _build/oofem/source-orig _build/oofem/source
cd _build/oofem/source && \
	patch -s -p0 < /home/zoheir/FEMDEM/Installation/oofem.diff
mkdir -p _build/oofem/build
cd _build/oofem/build && \
	cmake -DUSE_PYTHON_BINDINGS=ON _build/oofem/source
CMake Error: The source directory "/home/zoheir/FEMDEM/Installation/_build/oofem/build/_build/oofem/source" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:120: recipe for target 'oofem-cmake' failed
make: *** [oofem-cmake] Error 1

Before, I just made the directory (/_build/oofem/build/_build/oofem/source) and copied the source code from "/_build/oofem/build/source" to it in order to make it work. Looking back, it might have not been such a good idea. This error came up during the installation of both Yade and OOFEM. 

Any ideas why makefile looks for "/_build/oofem/build/_build/oofem/source" instead of "_build/oofem/source"?

**Comment by stranskyjan** [comment]
Sorry, I tried it with different, but not the default location. Now it should work

**Comment by zoheir1928** [comment]
I re-installed the code successfully. 

Thanks
