### ISSUE TITLE
Surfexample: getKeyByName and raise RuntimeError1

### ISSUE THREAD

**Issue by zoheir1928** [stranskyjan/dem-fem-coupling#11]
I get the following error when running surf1 example:

# set usePolyhedra=True if poly option is set
# use profiler or not
#python -m cProfile -o /tmp/surf1.pro surf1.py
# reset _yade.py script after running
sed -i 's/^usePolyhedra *=.*/usePolyhedra = False/' surf1_yade.py
python surf1_profile.py
Traceback (most recent call last):
  File "surf1_profile.py", line 5, in <module>
    tot = stats.getKeyByName('solveAt','demfemcoupling.py')
  File "/home/zoheir/FEMDEM/Installation/_build/install/profiler.py", line 19, in getKeyByName
    raise RuntimeError
RuntimeError
makefile:56: recipe for target 'profile' failed
make: *** [profile] Error 1

I would appreciate your thoughts

Cheers,
Zoheir

**Comment by stranskyjan** [comment]
Hi,
this was because the line generating the profiling info was commented in in the Makefile, but was uncommented in [this commit](https://github.com/stranskyjan/dem-fem-coupling/commit/b55de83d90566fd2a003db083feb3c8eaa004b3c). It should work with the new code.
Jan
