### ISSUE TITLE
 installation problem

### ISSUE THREAD

**Issue by wcc201834748** [stranskyjan/dem-fem-coupling#13]
Hi Jan,
          sorry to bother you, i meet some problems, when i run the 'makefile' ,and print 'make all' command. The error is showen like this:
          Segmentation fault (core dumped)
Makefile:105: recipe for target 'oofem-download' failed
make: *** [oofem-download] Error 139
         how can i solve this problem?

**Comment by stranskyjan** [comment]
Hello,
please provide more information:
- operating system and its version
- complete output of "male all" command

thanks
Jan

**Comment by wcc201834748** [comment]
Sorry i didn't describe it clearly. My operating sysytem is ubuntu 18.04 on virtual machine.
I directly enter the 'makefile' file in the terminal like :
cd /home/weicc/下载/dem-fem-coupling-master/installation
the run 'make all' in the terminal, after i download the oofem zip at 99%, then the error occured.
I'm sorry that my computer skills and English level are not very good, so I hope to seek your help.

**Comment by wcc201834748** [comment]
the full error report is shown as follow:
mkdir -p /home/weicc/下载/dem-fem-coupling-master/installation/_build/oofem
mkdir -p /home/weicc/下载/dem-fem-coupling-master/installation/_build/yade
mkdir -p /home/weicc/下载/dem-fem-coupling-master/installation/_build/install
rm -rf /home/weicc/下载/dem-fem-coupling-master/installation/_build/oofem/source-orig
wget http://www.oofem.org/cgi-bin/OOFEM/download.cgi?download=oofem-2.5.zip -O /home/weicc/下载/dem-fem-coupling-master/installation/_build/oofem/oofem.zip
--2020-05-15 21:22:12--  http://www.oofem.org/cgi-bin/OOFEM/download.cgi?download=oofem-2.5.zip
正在解析主机 www.oofem.org (www.oofem.org)... 147.32.130.71
正在连接 www.oofem.org (www.oofem.org)|147.32.130.71|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Found
位置：http://www.oofem.org/download/oofem-2.5.zip [跟随至新的 URL]
--2020-05-15 21:22:19--  http://www.oofem.org/download/oofem-2.5.zip
再次使用存在的到 www.oofem.org:80 的连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 14249792 (14M) [application/zip]
正在保存至: “/home/weicc/下载/dem-fem-coupling-master/installation/_build/oofem/oofem.zip”

ster/installation/_   4%[                   ] 657.12K  8.32KB/s    剩余 47m 34s^CMakefile:105: recipe for target 'oofem-download' failed
make: *** [oofem-download] 中断

**Comment by stranskyjan** [comment]
I have just tested it and it worked OK..
The problem is at `wget http://www.oofem.org/cgi-bin/OOFEM/download.cgi?download=oofem-2.5.zip -O $(oofem-zip)`, i.e. downloading the zip file. frim the 4% at your output, it seems it started, but did not finish for some reason..

Also I am a bit confused with `^C` in the output.. normally it means pressing "ctrl+C", which in the terminal means quit the running process.. is it the case? If so, please let it run until the very end error and copy-paste the output afterwards (with mouse and right-click -> copy, not ctrl+C)

**Comment by wcc201834748** [comment]
Thank you Jan,
i try it again, but there still a error occur ;
mkdir -p /home/weicc/下载/dem-fem-coupling-master/installation/_build/oofem
mkdir -p /home/weicc/下载/dem-fem-coupling-master/installation/_build/yade
mkdir -p /home/weicc/下载/dem-fem-coupling-master/installation/_build/install
rm -rf /home/weicc/下载/dem-fem-coupling-master/installation/_build/oofem/source-orig
wget http://www.oofem.org/cgi-bin/OOFEM/download.cgi?download=oofem-2.5.zip -O /home/weicc/下载/dem-fem-coupling-master/installation/_build/oofem/oofem.zip
--2020-05-16 09:01:09--  http://www.oofem.org/cgi-bin/OOFEM/download.cgi?download=oofem-2.5.zip
正在解析主机 www.oofem.org (www.oofem.org)... 147.32.130.71
正在连接 www.oofem.org (www.oofem.org)|147.32.130.71|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Found
位置：http://www.oofem.org/download/oofem-2.5.zip [跟随至新的 URL]
--2020-05-16 09:01:17--  http://www.oofem.org/download/oofem-2.5.zip
再次使用存在的到 www.oofem.org:80 的连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 14249792 (14M) [application/zip]
正在保存至: “/home/weicc/下载/dem-fem-coupling-master/installation/_build/oofem/oofem.zip”

ion/_build/oofem/oo 100%[==================>]  13.59M  11.9KB/s    剩余 0s    Segmentation fault (core dumped)
Makefile:105: recipe for target 'oofem-download' failed
make: *** [oofem-download] Error 139

**Comment by wcc201834748** [comment]
Dear Jan,
      i meet a new problem when i finish download the oofem, the error is shown as follow:
cmake -DUSE_PYTHON_BINDINGS=ON /home/weicc/下载/dem-fem-coupling-master/installation/_build/oofem/source
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning at /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindBoost.cmake:577 (message):
  **Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)**
Call Stack (most recent call first):
  /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:507 (find_package)


CMake Warning at /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindBoost.cmake:1727 (message):
  No header defined for python-py27; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:507 (find_package)


CMake Error at /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindBoost.cmake:2048 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:507 (find_package)


-- **Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)** 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:

 the line which i add the bold text above are the main reasons that i could not make successfully?

**Comment by stranskyjan** [comment]
> when i finish download the oofem

so the download works OK now?

> the error is shown as follow:

seems like boost is missing..
try `sudo apt install libboost-all-dev`

**Comment by wcc201834748** [comment]
thank you Jan,
     After accepting your suggestion, i successfully finnish the oofem part. But when the program runs to the yade part the error occur again, like this:
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 6244563 (6.0M) [application/x-tar]
正在保存至: “/home/weicc/下载/dem-fem-coupling-master/installation/_build/yade/yade.tar.bz2”

build/yade/yade.tar  99%[=================> ]   5.95M  8.40KB/s    剩余 3s    Makefile:135: recipe for target 'yade-download' failed
make: *** [yade-download] 段错误 (core dumped)
Sorry for making you so troublesome because of my ignorance, Thank you very much for your kind help

**Comment by stranskyjan** [comment]
This is the same problem as with Oofem. How did you solve that one?

**Comment by wcc201834748** [comment]
to be honest, i don't know how i solve that problem ,but the different is that one is 'Segmentation fault '. And i want know 'make all' is equal to 'make yade'+'make oofem'+'make make all top-dir=$HOME/programs/demfem j-oofem=4'?

**Comment by stranskyjan** [comment]
> 段错误 (core dumped)

this is also segmentation fault, or?

> 'make all' is equal to ...

`make all` [is equal to](https://github.com/stranskyjan/dem-fem-coupling/blob/master/installation/Makefile#L89)
```shell
make directories
make oofem
make yade
make install
```

**Comment by wcc201834748** [comment]
The problem seemed to disappear after I woke up, but still some problems appear, like: 
		/home/weicc/下载/dem-fem-coupling-master/installation/_build/yade/source
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
-- Found unsuitable Qt version "" from NOTFOUND
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Version is set to 2019.01a
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
-- GTS using gts-config /usr/bin/gts-config
-- Using GTS from /usr
-- Could NOT find GL2PS (missing: GL2PS_LIBRARY GL2PS_INCLUDE_DIR) 
-- CGAL not found.
-- Found NumPy: version "1.13.3" /usr/lib/python2.7/dist-packages/numpy/core/include
-- Could NOT find Loki (missing: LOKI_INCLUDE_DIR LOKI_LIBRARY) 
-- GCC Version >= 4.8. Adding -ftrack-macro-expansion=0
-- GCC Version >= 4.8. Adding -save-temps
-- GCC Version >= 4.9. Adding -fstack-protector-strong
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   python
--   thread
--   filesystem
--   iostreams
--   regex
--   serialization
--   system
--   date_time
--   chrono
--   atomic
--   Boost_VERSION: 106501
--   Boost_LIB_VERSION: 1_65_1
--   Boost_INCLUDE_DIRS: /usr/include
--   Boost_LIBRARIES: /usr/lib/x86_64-linux-gnu/libboost_python.so/usr/lib/x86_64-linux-gnu/libboost_thread.so/usr/lib/x86_64-linux-gnu/libboost_filesystem.so/usr/lib/x86_64-linux-gnu/libboost_iostreams.so/usr/lib/x86_64-linux-gnu/libboost_regex.so/usr/lib/x86_64-linux-gnu/libboost_serialization.so/usr/lib/x86_64-linux-gnu/libboost_system.so/usr/lib/x86_64-linux-gnu/libboost_date_time.so/usr/lib/x86_64-linux-gnu/libboost_chrono.so/usr/lib/x86_64-linux-gnu/libboost_atomic.so
CMake Error at /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Loki (missing: LOKI_INCLUDE_DIR LOKI_LIBRARY)
Call Stack (most recent call first):
  /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cMake/FindLoki.cmake:14 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:115 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/weicc/下载/dem-fem-coupling-master/installation/_build/yade/build/CMakeFiles/CMakeOutput.log".
See also "/home/weicc/下载/dem-fem-coupling-master/installation/_build/yade/build/CMakeFiles/CMakeError.log".
Makefile:149: recipe for target 'yade-cmake' failed
make: *** [yade-cmake] Error 1

**Comment by wcc201834748** [comment]
Dear Jan, 
   i solve the latest error by downloading all program that yade may need, And now i finsih the Oofem part by "make all" command (the error appeared when it come to yade part, should i repeat make Oofem again?), and use command "make yade" to finish the yade part. 
what is my next step? "make install"?

**Comment by wcc201834748** [comment]
Jan, 
i make install the two program, and try to run the example surfcontact, but how to show the simulation process?
Solving [Step number      299, Time    1.500000e+00]
# reset _yade.py script after running
sed -i 's/^usePolyhedra *=.*/usePolyhedra = False/' surf1_yade.py
python surf1_profile.py

total time for solution:     41.3855 s  (100.00 %)
getForcesFromDem:             0.5809 s  (  1.40 %)
applyForcesOnFem:             0.9721 s  (  2.35 %)
getDsplFromFem:               2.3016 s  (  5.56 %)
applyDsplOnDem:               0.7566 s  (  1.83 %)
yadeSolve:                    0.6826 s  (  1.65 %)
oofemSolve:                  36.0825 s  ( 87.19 %)
pvpython surf1_pv_sphs.py
make: pvpython: Command not found
Makefile:61: recipe for target 'pv' failed
make: *** [pv] Error 127

**Comment by stranskyjan** [comment]
the `pv` is just postprocessing and therefore not so important.. in case you want to solve also this:
`sudo apt install paraview`

**Comment by wcc201834748** [comment]
Thank you very much Jan,
   i finish the installation  and run the 4 examples successfully, Thank you for your patience and help. That really help me a lot. And i have a small question, how to output the  animation of the simulation process?

**Comment by stranskyjan** [comment]
if everything run successfully, there should be output files in /tmp directory. E.g. after running `surf1` example, I got `animation saved to /tmp/surf1.png` message at the end. in /tmp, I have surf1.00**.png files. There are also .vtk files saved if you want to output something else.

**Comment by wcc201834748** [comment]
yes Jan, there has notice  'animation saved to /tmp/multi1.png' ,but i can find this file in computer. And i try to export the animation of the simulation process into avi in Pareview but very time it report  errors and failed.

**Comment by stranskyjan** [comment]
> but i can find this file

can or cannot? :-)
it is not one file, but several files, e.g. `/tmp/multi1.0000.png`

> i try to export the animation of the simulation process into avi in Pareview

personally I have a bad experience with this approach, I prefer export pictures from Paraview and create a movie from them externally if needed

**Comment by wcc201834748** [comment]
Thank you Jan,
  you really help me a lot, I successfully completed the entire process, and export pictures from the tmp file.I really appreciate your patience and guidance, and I may ask you questions in the future, thank you.
  Best regard
