### ISSUE TITLE
multiscale

### ISSUE THREAD

**Issue by zhoug15** [stranskyjan/dem-fem-coupling#2]
Hi Jan:
I modified the loading time of your multi example:
1.I slowed down the loading speed in fem. I changed the loading time from 0.2s to 200s.(bcs are also changed)
2.I changed the dt from 2e-4 to 2e-2
3.In order to make sure the dem is stable, I changed the density in dem from 1e3 to 1e7 and set the gravity(0,0,0.0)

but it seems unstable, the strain seems relatively high(-0.0004 in step4).

Solving [Step number 0, Time 2.000000e-02]
('stress', Matrix3(-2.7232542208268342e-11,2.1607057838358735e-11,-7.565900182489134e-12, 2.1607057838358735e-11,-3.5733805174291325e-11,5.910176084244153e-12, -7.565900182489134e-12,5.910176084244153e-12,2.6839670851857137e-12))
('strain', Matrix3(0,0,0, 0,0,0, 0,0,0))
v:
Matrix3(0,0,0, 0,0,0, 0,0,0)

Solving [Step number 1, Time 4.000000e-02]
('stress', Matrix3(-1.083433491135522e-8,-1.3503776707434368e-8,1.7486952135573553e-8, -1.3503776707434368e-8,3.6347064127015305e-8,-2.926186112822691e-8, 1.7486952135573553e-8,-2.926186112822691e-8,8.99554151810844e-10))
('strain', Matrix3(0,0,0, 0,0,0, 0,0,0))
v:
Matrix3(0,0,0, 0,0,0, 0,0,0)

Solving [Step number 2, Time 6.000000e-02]
('stress', Matrix3(0.000015525172297319974,0.0000795526387192835,-0.00009283124932038486, 0.0000795526387192835,-0.0003630625371313257,0.0002590613138648092, -0.00009283124932038486,0.0002590613138648092,-0.00005720234018106285))
('strain', Matrix3(0.00005392650492956297,-1.7164899182052643e-18,-9.869235370759615e-6, -1.7164899182052643e-18,0.000053926504929562556,-9.869235370764533e-6, -9.869235370759615e-6,-9.869235370764533e-6,-0.00013675213675213405))
v:
Matrix3(0,1.3597608349867324e-16,2.353049132322896e-17, 1.3597608349867324e-16,0,6.850607918032826e-17, 2.353049132322896e-17,6.850607918032826e-17,0)

Solving [Step number 3, Time 8.000000e-02]
('stress', Matrix3(-11.3107674295793,1.7129703607246294,-2.787768422239802, 1.7129703607246294,-9.609769538283032,-0.23642769428808477, -2.787768422239802,-0.23642769428808477,-12.643860844491378))
('strain', Matrix3(0.00006091697779284176,4.488899208845239e-15,-0.000011148580698508899, 4.488899208845239e-15,0.00006091697779162887,-0.00001114858069311587, -0.000011148580698508899,-0.00001114858069311587,-0.0003103221564777195))
v:
Matrix3(1.2212453270876722e-13,1.1814561132037645e-13,1.6167065989061103e-13, 1.1814561132037645e-13,-1.6653345369377348e-14,-1.1915983548294906e-13, 1.6167065989061103e-13,-1.1915983548294906e-13,5.551115123125783e-14)

Solving [Step number 4, Time 1.000000e-01]
('stress', Matrix3(-7.308025222980424e8,9.503633740807763e7,-2.2945586023590547e8, 9.503633740807763e7,-9.180035574511294e8,1.3301196286263055e8, -2.2945586023590547e8,1.3301196286263055e8,-9.263253771518726e8))
('strain', Matrix3(0.000014233498104035896,-2.3639298424766302e-11,-2.6049070587392296e-6, -2.3639298424766302e-11,0.000014233512498104343,-2.6049467336185456e-6, -2.6049070587392296e-6,-2.6049467336185456e-6,-0.00045189774370015776))
v:
Matrix3(-5.176525874617255e-10,-1.0401586226850383e-9,-9.210391726013966e-10, -1.0401586226850383e-9,-1.3655188091377113e-10,5.564194956105476e-10, -9.210391726013966e-10,5.564194956105476e-10,-5.627942556429844e-10)

However, the loading speed must be slow in my example.
Is there any way to make dt a little larger?
I attached my multi_yade multi_oofem and multi.

[multi_yade_oofem.zip](https://github.com/stranskyjan/dem-fem-coupling/files/2906088/multi_yade_oofem.zip)

yours, Joe

**Comment by zhoug15** [comment]
Hi Jan:
I attached my multi_yade multi_oofem and multi files above.
Besides reduce dt, is there any other ways to keep the dem spheres stable?
yours,
Joe

**Comment by stranskyjan** [comment]
Hi Joe,

I have a new system and have some troubles compiling the stuff so I cannot test your code right now.

Concerning stability, critical time of explicit simulations is given by sqrt(stiffness/density). So instead of reducing dt, you can reduce stiffness or increase density, but you change the physics of the problem.
If the loading speed must be slow, then probably you will have to use more computation time.. or use a different strategy, like implicit time integration, but then my code is not ready-to-use..
