### ISSUE TITLE
multiscale_2

### ISSUE THREAD

**Issue by zhoug15** [stranskyjan/dem-fem-coupling#3]
Hi Jan:
I don't understand why there are 2 engines and 2 materials in the multi1_yade.py. 
I saw the RVE generation file "prepareRVE.py" in trunk/example/FEM-DEM folder and found frictmat only and also only 1 engine was used.
I tried to delete cmpMat and its related engine, but it got error.
What are the differences of the 2 engines(material) and what are they used for?
Yours, Joe
BTW, did you compile the stuff on your new system? If so, I can attach my file here.

**Comment by stranskyjan** [comment]
Hi Joe,

> I don't understand why there are ... 2 materials in the multi1_yade.py.
> What are the differences of the 2 material and what are they used for?

there are two materials just to show a simulation with two materials :-) they differ in stiffness (which can be seen from the results)

> I don't understand why there are 2 engines ... in the multi1_yade.py.
> I saw the RVE generation file "prepareRVE.py" in trunk/example/FEM-DEM folder and found frictmat only and also only 1 engine was used.
> What are the differences of the 2 engines and what are they used for?

First O.engines is for randomPeriPack function used for pre-processing (corresponds to prepareRVE.py you mentioned).
In randomPeriPack, only FrictMat is used.

The second occurrence in the code (actually there is separate O.engines for each FEM integration point) is for actual simulation. 

> but it got error.

please post here your actual code and the errors

> BTW, did you compile the stuff on your new system? If so, I can attach my file here.

No (see updated README) :-( I will install Ubuntu 16.04 (where it used to work) on virtualbox..

cheers
Jan

**Comment by zhoug15** [comment]
Thank you very much!
That solved my problem!

**Comment by zhoug15** [comment]
Hi Jan:
I checked the codes in oofem and found that it makes no sense to set plastic stiffness.
Here are codes about function 'setIPValue' in oofem:
int
StructuralMaterial :: setIPValue(const FloatArray &value, GaussPoint *gp, InternalStateType type)
{
    StructuralMaterialStatus *status = static_cast< StructuralMaterialStatus * >( this->giveStatus(gp) );
    if ( type == IST_StressTensor ) {
        status->letStressVectorBe(value);
        return 1;
    } else if ( type == IST_StrainTensor ) {
        status->letStrainVectorBe(value);
        return 1;
    } else if ( type == IST_StressTensorTemp ) {
        status->letTempStressVectorBe(value);
        return 1;
    } else if ( type == IST_StrainTensorTemp ) {
        status->letTempStrainVectorBe(value);
        return 1;
    } else {
        return 0;
    }
}

In fact, in nldeidynamic engineering model, we don't need to caculate the stiffness matrix. The internal load forces are caculated using stress vector(sigma),
InternalForces = K*u(t)=intergrate(B^T*sigma)
Although it doesn't have any influence on the result, it costs more computation resources.
Yours,
Joe

**Comment by stranskyjan** [comment]
Hi Joe,

plastic STRAIN, not stiffness is set..

But looking to the code, I think you are right and mere
###
	def applyStressOnFem(self):
		liboofem = self.fem._lib
		for ip,stress in zip(self.ips,self.stresses):
			ip = self.fem.giveIntegrationPoint(ip)
			val = self._stressMatrix2FloatArray(stress)
			mat.setIPValue(plasticStrain,ip,self._IST_PlasticStrainTensor)
###
should be enough..

The stiffness and plastic strain computation and setting is probably a relic from the times when I did not use StructuralMaterialSettable but a plasticity material, where stress was computed as
stress = stiffness*(strain-plasticStrain)

cheers
Jan

**Comment by wcc201834748** [comment]
@zhoug15 sorry to bother you. I am a new learner of Github, and poor in english.i have some problem in  installation ,can i ask problem in chinese ? I gauss you are chinese too.

**Comment by zhoug15** [comment]
@wcc201834748 可以的，我的邮箱13996047780@163.com
