### ISSUE TITLE
About constantEdgeLoad and constantSurfaceLoad In Oofem

### ISSUE THREAD

**Issue by zhoug15** [stranskyjan/dem-fem-coupling#4]
Hi Jan:
In my model, I want to add constantSurfaceload to the element. But I don't know how to add surface load or edge load to it. 
Now I use nodalload to model constant edge load. But when the normal vector of the element surface changed, the componentArray of nodalload will change, thus constant nodalload may not be suitable.
So how to add constantsurfaceload to element surface in the python module of oofem?
Yours,
Joe

**Comment by stranskyjan** [comment]
Hi Joe,
I am sorry, I have no experience with edge/surface loads.. Have a look at oofem input manual (femdem/oofem/source/doc/oofemInput/oofemInput.pdf, section 7.9). The usage in python script is "usual", e.g.:
load = liboofem.constantEdgeLoad(id,domain,...) # only a few classes can be made this way
or
laod = liboofem.generalBoundaryCondition(name,id,domain,...) # a more general method accepting any name

Jan
