### ISSUE TITLE
Something wrong with loading application of the surface coupling of FEM/DEM

### ISSUE THREAD

**Issue by Dez2018** [stranskyjan/dem-fem-coupling#6]
Hi, Jan~
I tried to post this question on the yadepad. 
I want to add load on the certain nodes in FEM during the surface coupling of FEM/DEM, but something was wrong by the procedure with errror prompt as following:
--------------------------------
Error:(/home/.../oofemlib/domain.C:353)
 In Domain::giveload, number : 1:
 cannot cast boundary condition 1 to Load class
 ------------------------------------------------------------
Here was part of my script for FEM as following:
############
 import liboofem
def readUnvFile111(fName):
 ...
 ## read the mesh file of UNV and get the nodes ##
 global Nodes4unv,Elems4unv111
 Nodes4unv,Elems4unv111 = readUnvFile111('/tmp/membrane3Dtr12.unv')
 ## read the nodes and elements ##

class Node:
  def __init__(self,id,coords):
   self.id = id
   self.coords = list(coords)
   self.bcs = [0,0,0]
  def toOofem(self):
   kw = dict(coords=self.coords)
   if any(self.bcs):
    kw["bc"] = self.bcs
   return liboofem.node(self.id,domain,**kw)

def createOofemNodes():
  nodes = [Node(-1,tuple(nodexyz)) for _, (nodexyz) in enumerate(Nodes4unv)]
  for i,n in enumerate(nodes):
   n.id = i+1
   if n.coords[2] == 0.17:
    n.bcs = [1,1,1]
   elif n.coords[2] == 0.72:
    n.bcs = [1,1,1]
  return [n.toOofem() for n in nodes]
 ##
 class Shell4tr:
  def __init__(self,id,nodes):
   self.id = id
   self.nodes = list(nodes)
  def toOofem(self):
   return liboofem.element("LTRSpace",self.id, domain, nodes=self.nodes, mat=1, crossSect=1, nlgeo=1)

def createOofemElems():
  elems = []
  #for _, (NumId41) in enumerate(Elems4unv41):
   #elems.append(Shell3tr(-1,(NumId41)))
  for _, (NumId111) in enumerate(Elems4unv111):
   elems.append(Shell4tr(-1,(NumId111)))
  for i,e in enumerate(elems):
   e.id = i+1
  return [e.toOofem() for e in elems]
 ### all above was get the mesh information from unv and built the geom of object in fem##

def sortNodes():
  fxpNodes = []
  fxnNodes = []
  fypNodes = []
  fynNodes = []
  for i in xrange(domain.giveNumberOfDofManagers()):
   a = domain.giveDofManager(i+1).giveCoordinates()
   c = [a[j] for j in xrange(3)]
   if abs(c[0]-0.04)<0.006:
    fxpNodes.append(i+1)
   if abs(c[0]-0.36)<0.006:
    fxnNodes.append(i+1)
   if abs(c[1]-0.04)<0.006:
    fypNodes.append(i+1)
   if abs(c[1]-0.36)<0.006:
    fynNodes.append(i+1)
  return fxpNodes,fxnNodes,fypNodes,fynNodes

## according to the above, I extracted the nodes for loading##

def loadmembrane():
  loadxp = liboofem.FloatArray()
  loadxp.resize(3)
  loadxp.zero()
  loadxp[0] = 3 #x=0.045 & 0.035
  loadxn = liboofem.FloatArray()
  loadxn.resize(3)
  loadxn.zero()
  loadxn[0] = -3 #x=0.355 & 0.365
  loadyp = liboofem.FloatArray()
  loadyp.resize(3)
  loadyp.zero()
  loadyp[1] = 3 #x=0.045 & 0.035
  loadyn = liboofem.FloatArray()
  loadyn.resize(3)
  loadyn.zero()
  loadyn[1] = -3 #x=0.355 & 0.365
  for ixp in fxpNodes:
   lxp = domain.giveLoad(ixp)
   axp = lxp.giveComponentArray()
   axp.add(loadxp)
   lxp.setComponentArray(axp)
  for ixn in fxnNodes:
   lxn = domain.giveLoad(ixn)
   axn = lxn.giveComponentArray()
   axn.add(loadxn)
   lxn.setComponentArray(axn)
  for iyp in fypNodes:
   lyp = domain.giveLoad(iyp)
   ayp = lyp.giveComponentArray()
   ayp.add(loadyp)
   lyp.setComponentArray(ayp)
  for iyn in fynNodes:
   lyn = domain.giveLoad(iyn)
   ayn = lyn.giveComponentArray()
   ayn.add(loadyn)
   lyn.setComponentArray(ayn)

###and I apply the load on these nodes###

############################################################
 # engngModel
 problem = liboofem.engngModel("nldeidynamic",1,nSteps=5,dumpCoef=.1,deltaT=10000,outFile="/tmp/membrane_oofem.out")

# domain
 domain = liboofem.domain(1, 1, problem, liboofem.domainType._3dMode, tstep_step=10000, dofman_all=True, element_all=True)
 problem.setDomain(1, domain, True)

# vtkxml
 vtkxmlModule = liboofem.vtkxml(1,problem,tstep_step=10000,vars=[1,6],primvars=[1,4])
 #vtkxmlModule = liboofem.vtkxml(1,problem,tstep_step=10000)
 exportModuleManager = problem.giveExportModuleManager()
 exportModuleManager.resizeModules(1)
 exportModuleManager.setModule(1,vtkxmlModule)

# boundary condition and time function
 ltf = liboofem.loadTimeFunction("constantFunction",1,f_t=0)
 bc = liboofem.boundaryCondition(1, domain, loadTimeFunction=1, prescribedValue=0.0)

# nodes
 nodes = createOofemNodes()

# material and cross section
 mat = liboofem.isoLE(1, domain, d=1200, E=1.2e7, n=0.48, tAlpha=0)
 cs = liboofem.simpleCS(1, domain,)

# elements
 elems = createOofemElems()

# add eveything to domain (resize container first)
 domain.resizeDofManagers(len(nodes))
 for n in nodes:
  domain.setDofManager(n.number, n)
 domain.resizeElements(len(elems))
 for e in elems:
  domain.setElement(e.number, e)
 domain.resizeMaterials(1)
 domain.setMaterial(1, mat)
 domain.resizeCrossSectionModels(1)
 domain.setCrossSection(1, cs)
 domain.resizeBoundaryConditions(1)
 domain.setBoundaryCondition(bc.number, bc)
 domain.resizeFunctions(1)
 domain.setFunction(ltf.number, ltf)

vtkxmlModule.initialize() # (!)

######################## extract the nodes and apply the load on them ###
fxpNodes,fxnNodes,fypNodes,fynNodes = sortNodes()
 loadmembrane()
#####
 so did something wrong with the boundary or loading ?

Best regards,
Dez

**Comment by zhoug15** [comment]
@Dez2018 
Hi,
Error:(/home/.../oofemlib/domain.C:353)
In Domain::giveload, number : 1:
cannot cast boundary condition 1 to Load class

In order to add load to oofem dofs, you should create nodelloads for them.
See line 266-283 in demfemcoupling.py
 
Yours,
Joe

**Comment by Dez2018** [comment]
> 
> 
> @Dez2018
> Hi,
> Error:(/home/.../oofemlib/domain.C:353)
> In Domain::giveload, number : 1:
> cannot cast boundary condition 1 to Load class
> 
> In order to add load to oofem dofs, you should create nodelloads for them.
> See line 266-283 in demfemcoupling.py
> 
> Yours,
> Really thanks Joe~ I will try and tell you the results whether it works~ 
Best regards,
Dez

**Comment by Dez2018** [comment]
> 
> 
> @Dez2018
> Hi,
> Error:(/home/.../oofemlib/domain.C:353)
> In Domain::giveload, number : 1:
> cannot cast boundary condition 1 to Load class
> 
> In order to add load to oofem dofs, you should create nodelloads for them.
> See line 266-283 in demfemcoupling.py
> 
> Yours,
> Joe
###########################################
Hi Joe~

I try to add the force on some nodes of the model as you mentioned like following:

in line 266-283 in demfemcoupling.py
I append the code in function nLoad(i) as following:

#def nLoad(i):
#      ret = flib.NodalLoad(i,d)
#      ca = flib.FloatArray(3)
#      ca.zero()
################ The following were added by me #####
#1      for i in xrange(d.giveNumberOfDofManagers()):
#2          a = d.giveDofManager(i+1).giveCoordinates()
#3           c = [a[j] for j in xrange(3)]
#4           if c[0] > -0.05 and c[0] < 0.05:
#5               ca[2] = -10
#6      ret.setComponentArray(ca)
#7      ret.setFunction(nfs)
#8      return ret
###############
during Line 4-5 to sort the nodes for load
but when I check the result , there was still no load on the object?

Did something wrong with the code?

Thanks~
Dez

**Comment by zhoug15** [comment]
@Dez2018 
Hi Zhang De:
I guess the loads were set to 0 when coupled. See line 311-316. You can add loads for your points in module applyForcesOnFem(self). You can also use constant edgeload or constant surface load (however you need to modify some codes in oofemlib.cpp).
For more information, you can read oofemlib.cpp in oofem-master/bindings/python/ and see how the codes work. 
Yours,
Joe

**Comment by Dez2018** [comment]
> 
> 
> @Dez2018
> Hi Zhang De:
> I guess the loads were set to 0 when coupled. See line 311-316. You can add loads for your points in module applyForcesOnFem(self). You can also use constant edgeload or constant surface load (however you need to modify some codes in oofemlib.cpp).
> For more information, you can read oofemlib.cpp in oofem-master/bindings/python/ and see how the codes work.
> Yours,
> Joe

Hi Joe~
I tried again, but it still didn't work
I add the code in  line 255-280 as modify the function of 'def __init__(self,*args):'
#1 vsc = [v.coords for v in self.femMesh.vertices]
#2 def nLoad(i):
#3       ret = flib.NodalLoad(i,d)
#4       ca = flib.FloatArray(3)
#5       ca.zero()
#6       ii = i-nbcs-1
#7       One = Vector3(0,0,2)
#8       PosZ = (vsc[ii]).dot(One)
#9       if PosZ > 0.1:
#10            ca[2] = -10
#11     ret.setComponentArray(ca)
#12     ret.setFunction(nfs)

##############
I don't know why it didn't work, even I moved the restrict condition as no "if...", so that all vertices load "ca[2] = -10", it still no load on the vertices

Could please tell me what's the problem with that?
Thank you

Yours,
Dez~

**Comment by Dez2018** [comment]
Hi Jan and Joe~
I modifed the function "def applyForcesOnFem(self)" as flowing:
#before that in "__init__ " part, I defined the global parameter like:
# global vsc
# vsc = [v.coords for v in self.femMesh.vertices]
# After that, I modified the function of "applyForcesOnFem(self)" like
import math
global vsc
for i, v in enumerate(self.forces):
     if vsc[i][2] < 0.5:
          self.forces[i] = self.forces[i]+ Vector3(-0.1,-0.1,0)
     for load,force in zip(self.loads,self.forces):
          ca = self.fem._lib.FloatArray(3)
      load.setComponentArray(ca)
############
When I tried all above, and found that the sequence of the "self.femMesh.vertices" changed at each step, which caused that the order of self.forces[i] counld not match the vertices that I intended to changed. So how to track the constant order of self.forces at each step?

Yours, 
Dez

**Comment by Dez2018** [comment]
Hi Jan and Joe~
I have solved the problem. I check the vertices coordinates and loading force. The result shows that self.femMesh.vertices changed each coupling time, but they didn't vary each step.
Thank you for your reminder and help~
Best regards,
Dez~
