### ISSUE TITLE
weight of vertices

### ISSUE THREAD

**Issue by zhoug15** [stranskyjan/dem-fem-coupling#7]
Hi Jan:
In line 728-733,
	w1 = (cp-v1).cross(cp-v3).dot(cp-v2)
	w2 = (cp-v1).cross(cp-v2).dot(cp-v4)
	w3 = (cp-v1).cross(cp-v4).dot(cp-v3)
	w4 = (cp-v2).cross(cp-v3).dot(cp-v4)
I don't really understand, maybe
	w4 = (cp-v1).cross(cp-v3).dot(cp-v2)
	w3 = (cp-v1).cross(cp-v2).dot(cp-v4)
	w2 = (cp-v1).cross(cp-v4).dot(cp-v3)
	w1 = (cp-v2).cross(cp-v3).dot(cp-v4)?
Yours,
Joe

**Comment by stranskyjan** [comment]
Hi Joe,
yes, your modifications seems to be right, sorry :-)
Jan
